Portfolio setup and mobile skeleton project
Malcom-Charlie/Portfolio-setup-n-mobi-sekeleton pull request #1
Opened 2022-05-27 01:02 UTC by Malcom-Charlie

> These are the project requirements that have been met

- set up a new repository and prepare it for development using best practices (e.g. linters).
- build the first 2 sections of the mobile website using the template you chose in the previous step.

### HTML/CSS requirements

- Follow microverse list of [best practices for HTML & CSS]
- For this project, I should use the [HTML&CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css)
- The 2 sections you need to build for this project are:

    - the toolbar (or header):
![toolbar-mobile](https://user-images.githubusercontent.com/61559987/170607043-ffdf79fd-6ccb-49fe-b1aa-f13bf7e3bcc9.png)

    - the headline section (right after the header):
![headline-mobile](https://user-images.githubusercontent.com/61559987/170607101-6f897b3c-eabe-4034-96fa-1ee4e59ef9e1.png)

A screenshot was included but advised to follow the template that you chose.
    
- Use Flexbox in all 2 sections.
- Don't implement any functionality that requires JavaScript, like opening the menu or creating dropdowns.
- Stick to the design as much as possible (e.g. font, colors, images, tests, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
- Implement the button interactions (enable, hover, etc.).

2022-05-27 02:22 UTC, Ginohmk requested changes
Hi @Malcom-Charlie , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![you-are-near](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- Linters all green :+1: 
- Good indentation of code :1st_place_medal: 
- Good commit messages :100: 
- Good PR summary :+1: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._





Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 02:22 UTC, koachcode commented on index.html
> +      </nav>
- Please wrap the `<nav>` tag inside a `<header>`, so as to follow the proper HTML sematics. so you have something like 
```html
<header>
<nav>
.....
</nav>
</header>
```

- Please make use of the proper spacing (margin and padding), as used in the Figma design, so as to be in line with the detailed design.

##### Figma design

![Screenshot from 2022-05-27 03-06-20](https://user-images.githubusercontent.com/58771507/170615584-eaee7392-e3a9-4c9d-a5c2-239e78c4ddab.png)


##### Your design

![Screenshot from 2022-05-27 03-07-43](https://user-images.githubusercontent.com/58771507/170614432-2d74add2-3889-4d87-9450-cee4abd43001.png)


- [Optional] I would suggest you, take your logo out of the `<nav>` tag and directly inside your `<header>` tag, like so
```html
<header>
    <img class="logo" src="./elements/lg.png" alt="Logo">
    <nav class="dcp1 navbar">
          <img class="menu" src="./elements/Enabled.jpg" alt="Humbugger menu">
      </nav>
</header>
```  
Then perform the necessary CSS to align the elements properly on the webpage :+1:

2022-05-27 02:22 UTC, koachcode commented on index.html
> +      <article class="dcp1 art1">
- Please replace this `<article>` tag with a `<section>` tag. **Note:** Do note forget the corresponding closing tag as well

2022-05-27 02:22 UTC, Ginohmk commented on index.html
> +          </h4>
- Please replace the `<h4>` tag with an `<h1>` tag, so as to have a well structured semantically correct HTML code
- Please the sentence ` I’m Sir_Malcom Glad to see you!`, make use of the correct font family which is `Poppins` and you should employ a `<br>` tag in the appropriate place, so as to make your project design more similar to the Figma design.
- Please use the appropriate spacing (padding and margins) as described in the figma design. 
##### Figma design
![Screenshot from 2022-05-27 02-58-34](https://user-images.githubusercontent.com/58771507/170613475-a627f990-f0c9-4c59-8d6c-6f9f6d6c8828.png)

##### Your design
![Screenshot from 2022-05-27 02-59-34](https://user-images.githubusercontent.com/58771507/170613583-a550ee4c-39b4-40a0-9544-10d7ddf2b364.png)

2022-05-27 02:22 UTC, Ginohmk commented on index.html
> +      <article class="dcp1 art2">
- Please change the `<article>` tag to a `<p>` tag so as to stick with the proper HTML semantics

2022-05-27 02:22 UTC, Ginohmk commented on index.html
> +      </div>
- Please make use of a `<ul>` here with the corresponding li with an `<a>` tag as those social icon media icons with be a link to your corresponding social pages. for example

```html
<ul>
  <li> <a href = "#" target = "_blank"> <img src="/elements/gthb.png" alt="github"> </a></li>
  <li> <a href = "#" target = "_blank"> <img src="/elements/lnkin.png" alt="linkedin"></a></li>
  <li> <a href = "#" target = "_blank"> <img src="/elements/twtr.png" alt="twitter"> </a></li>
  <li> <a href = "#" target = "_blank"><img src="/elements/m.png" alt="m"></a></li>
  <li> <a href = "#" target = "_blank"> <img src="/elements/chill.png" alt="chill"> </a></li>
</ul>
```
Then use CSS flex to style it appropriately. if you find this confusing, you can reach me on slack so I explain better `@kanu mike chibundu`

2022-05-27 09:57 UTC, danmainah requested changes
Hi  @Malcom-Charlie, 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good PR and Description


 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 09:57 UTC, danmainah commented on index.html
> +        <li><a href="#" target="_blank"><img src="/elements/chill.png" alt="chill"></a></li>
- [ ] [OPTIONAL] Kindly add dot (./) in your URL , like you did in this line ` <img class="dcp1 social" src="./elements/ltscnnct.jpg" alt="lets connect">`, this will ensure your icons are visible even when the page is opened in githack.
- [x] Also check the design as the previous reviewer requested, check the comparison with the Figma design below;

Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/170676968-b0c5bd35-aa27-4e13-a607-ce5d33ed0dbe.png) |  ![image](https://user-images.githubusercontent.com/61408860/170677022-d01bdd01-08ed-410a-bb79-8950824a236d.png)

2022-05-27 11:11 UTC, Malcom-Charlie commented on index.html
> +        <li><a href="#" target="_blank"><img src="/elements/chill.png" alt="chill"></a></li>
This is weird it's working on my end what could be the reason

2022-05-27 11:18 UTC, Malcom-Charlie commented on index.html
> +        <li><a href="#" target="_blank"><img src="/elements/chill.png" alt="chill"></a></li>
@danmainah Don't understand what might be causing this its working well on my end

2022-05-27 13:23 UTC, chrystalme approved these changes
## Hi @Malcom-Charlie , 

## Project Status ✔️  Approve
![giphy](https://user-images.githubusercontent.com/12239821/170706403-be7f2a9f-e5a4-4216-82b6-0c9f7ce2f0ad.gif)
In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

Although I have marked this project as approved, you have some requirements to meet going forward.
## Optional Requirement
- Your git commits are not following the professional standard for git commits. Kindly start the sentence of each commit with a capital letter. 
|Good commit ✔️ | Bad commit ❌ |
|---|---|
|Update linters setup|updated linters setup|
|Add HTML components| added HTML components|
- This project uses the mobile first approach to web development. Your design has a fixed with for the mobile view. It is advisable and a good practise to start with mobile view and then adjust your design using `@media queries` for the other views
- Also, I left some inline comments for you. Kindly attend to them before you merge this pull request
Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Also, you can reach me on [Twitter](https://twitter.com/afam_ifeanyi) or [Slack](https://microverse-community.slack.com/team/U019ZC99KFA)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 13:23 UTC, chrystalme commented on index.html
> +    <img class="logo" src="./elements/lg.png" alt="Logo">
In the design, this element is a text. Kindly adjust your design to meet this requirement. 
![image](https://user-images.githubusercontent.com/12239821/170706164-ba5acdfe-7d26-48f6-bf4b-a98e2d580415.png)

2022-05-27 13:41 UTC, chrystalme commented on index.html
> +    <img class="logo" src="./elements/lg.png" alt="Logo">
Also, this should be a link to the homepage so, use a `<a>` tag to wrap the text.

2022-05-27 14:37 UTC, merged

2022-06-03 22:56 UTC, leonardodiasb reviewed
# INVALID ❌ ❌ ❌ 

Hi @Malcom-Charlie , 👋

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌
 - You have submitted a Pull Request that has already been approved. That's great, but I cannot review an already approved PR. Kindly open a new PR and submit it like it is the first submission (with the descriptive title and description) so we can approve it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

----
_Invalid Code Review Request does not count into the code reviews limit._